
--create a new pdb from seed from cdb$root

conn / as sysdba

CREATE PLUGGABLE DATABASE pdb_test
 ADMIN USER pdbtestadmin IDENTIFIED BY ABcd##1234;
ALTER PLUGGABLE DATABASE pdb_test OPEN; 

ALTER PLUGGABLE DATABASE pdb_test CLOSE IMMEDIATE;

ALTER PLUGGABLE DATABASE pdb_test OPEN RESTRICTED;

SELECT CON_ID, OPEN_MODE, RESTRICTED FROM V$PDBS WHERE NAME='PDB_TEST';


-- change the pdb global name

ALTER SESSION SET CONTAINER=PDB_TEST;

SHOW CON_NAME;

ALTER PLUGGABLE DATABASE pdb_test RENAME GLOBAL_NAME to pdb02;

SELECT CON_ID, OPEN_MODE, RESTRICTED FROM V$PDBS WHERE NAME='PDB02';

conn / as sysdba

show user;
show con_name;

ALTER PLUGGABLE DATABASE pdb2 CLOSE IMMEDIATE;

ALTER PLUGGABLE DATABASE pdb2 OPEN;

SELECT CON_ID, OPEN_MODE, RESTRICTED FROM V$PDBS;
