-- Run on catalog database (PDB)


SELECT INSTANCE_NAME,STATUS FROM V$INSTANCE;
SHOW PARAMETER SERVICE_NAMES;

CREATE TABLESPACE rcat_tbs;

CREATE USER rcowner IDENTIFIED BY rcpass
DEFAULT TABLESPACE rcat_tbs
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON rcat_tbs;

GRANT RECOVERY_CATALOG_OWNER TO rcowner;
